version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - app_network
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

networks:
  app_network:
    driver: bridge
